config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :menu_items, except: :show do
      member do
        get :children
      end
    end
  end
end

app/models/spree/menu_item.rb
module Spree
  class MenuItem < ActiveRecord::Base
    before_create :set_item_position
    before_save :assign_default_values

    belongs_to :parent,
               foreign_key: :parent_id,
               class_name: 'Spree::MenuItem'
    has_many :children,
             class_name: 'Spree::MenuItem',
             foreign_key: :parent_id,
             dependent: :destroy

    validates :name, presence: true

    default_scope { order(position: :asc) }

    scope :top_level, -> { where(parent_id: nil) }

    protected

    def set_item_position
      # self.position = MenuItem.where(parent_id: self.parent_id).count
      self.position = MenuItem.where(parent_id: parent_id).count
    end

    def assign_default_values
      %w(url item_class item_id item_target parent_id).each do |key|
        self[key] = nil if self[key].blank?
      end
    end
  end
end

app/controllers/spree/admin/menu_items_controller.rb
module Spree
  module Admin
    class MenuItemsController < BaseController
      before_action :set_menu_item, only: [:edit, :update, :destroy, :children]

      def index
        @menu_items = Spree::MenuItem.top_level
        respond_to do |format|
          format.html
          format.json { render :children, status: :ok }
        end
      end

      def new
        @menu_item = Spree::MenuItem.new
      end

      def create
        @menu_item = Spree::MenuItem.new(menu_item_params)
        respond_to do |format|
          if @menu_item.save
            format.html { submit_success_redirect(:create) }
            format.json { render :show, status: :created }
          else
            format.html { render :new }
            format.json { render_json_error }
          end
        end
      end

      def update
        respond_to do |format|
          if @menu_item.update(menu_item_params)
            organize_items
            format.html { submit_success_redirect(:update) }
            format.json { render :show, status: :created }
          else
            format.html { render :edit }
            format.json { render_json_error }
          end
        end
      end

      def destroy
        @menu_item.destroy
        respond_to do |format|
          format.html { submit_success_redirect(:destroy) }
          format.json { head :no_content }
        end
      end

      def children
        @menu_items = Spree::MenuItem.find(params[:id]).children
        respond_to do |format|
          format.json { render :children, status: :ok }
        end
      end

      protected

      def submit_success_redirect(type)
        scope = 'navigator.admin.flash.success'
        redirect_to admin_menu_items_path, flash: {
          success: Spree.t(type, name: @menu_item.name, scope: scope)
        }
      end

      def render_json_error
        render json: @menu_item.errors, status: :unprocessable_entity
      end

      def set_menu_item
        @menu_item = Spree::MenuItem.find(params[:id])
      end

      def permitted_menu_item_attributes
        [
          :name,
          :url,
          :item_id,
          :item_class,
          :item_target,
          :parent_id,
          :position
        ]
      end

      def menu_item_params
        if params[:menu_item][:parent_id] == 'menu_tree'
          params[:menu_item][:parent_id] = nil
        end
        params.require(:menu_item).permit(permitted_menu_item_attributes)
      end

      def organize_items
        Spree::MenuItem.where(parent_id: menu_item_params[:parent_id])
          .order(updated_at: :desc)
          .map(&:id)
          .each_with_index do |id, index|
          Spree::MenuItem.find(id).update_attributes(position: index)
        end
      end
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper
    def navigator_menu
      menu_items = Spree::MenuItem.top_level
      if menu_items.any?
        navigator_levels(menu_items)
      else
        navigator_default
      end
    end

    protected

    def navigator_levels(menu_items)
      menu_items.each_with_object([]) do |menu_item, items|
        item = navigator_item(menu_item)

        if menu_item.parent_id.present?
          item[:options] = { container_class: 'menu-children' }
        end

        if menu_item.children.any?
          item[:items] = navigator_levels(menu_item.children)
        end

        items << item
      end
    end

    def navigator_default
      [
        navigator_item(Spree::MenuItem.new(
          id:      0,
          name:    Spree.t(:home),
          url:     spree.root_path,
          item_id: 'home-link'
        ))
      ]
    end

    def navigator_item(item)
      {
        key:     item.id,
        name:    item.name,
        url:     item.url,
        options: {
          id:    item.item_id || "menu_item_#{item.id}",
          class: "menu-item #{item.item_class || "menu-item-#{item.id}"}",
          link:  { target: item.item_target || nil }
        }
      }
    end
  end
end

app/views/spree/admin/menu_items/_form.html.erb
<fieldset data-hook="admin_menu_items_form_fields" class="no-border-top">
  <% if f.object.id.nil? %>
    <legend align="center"><%= Spree.t('navigator.admin.fieldset.legend.new') %></legend>
  <% else %>
    <legend align="center"><%= Spree.t('navigator.admin.fieldset.legend.edit') %></legend>
  <% end %>

  <div class="row">
    <div class="field">
      <%= f.label :name, Spree.t('navigator.admin.label.name') %>
      <%= f.text_field :name, class: 'fullwidth' %>
    </div>

    <div class="field">
      <%= f.label :url, Spree.t('navigator.admin.label.url') %>
      <%= f.text_field :url, class: 'fullwidth' %>
    </div>

    <div class="field">
      <%= f.label :item_id, Spree.t('navigator.admin.label.id') %>
      <%= f.text_field :item_id, class: 'fullwidth' %>
    </div>

    <div class="field">
      <%= f.label :item_class, Spree.t('navigator.admin.label.class') %>
      <%= f.text_field :item_class, class: 'fullwidth' %>
    </div>

    <div class="field">
      <%= f.label :item_target, Spree.t('navigator.admin.label.target') %>
      <%= f.text_field :item_target, class: 'fullwidth' %>
    </div>
  </div>

  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <% if f.object.id.nil? %>
      <%= button Spree.t('actions.create'), 'refresh' %>
    <% else %>
      <%= button Spree.t('actions.update'), 'refresh' %>
    <% end %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_menu_items_path, class: 'button' %>
  </div>
</fieldset>

app/views/spree/admin/menu_items/_list.html.erb
<% items.each do |item| %>
  <tr id="<%= spree_dom_id item %>" class="<%= cycle('odd', 'even')%>">
    <td><% if is_child %>----<% end %><%= item.name %></td>
    <td><%= item.url %></td>
    <td class="actions">
      <%= link_to_edit(item, { no_text: true, url: edit_admin_menu_item_path(item.id) }) %>
      <%= link_to_delete(item, { no_text: true, url: admin_menu_item_path(item.id) }) %>
    </td>
  </tr>

  <% if item.children.any? %>
    <%= render partial: 'spree/admin/menu_items/list', locals: { items: item.children, is_child: true } %>
  <% end %>
<% end %>

app/views/spree/admin/menu_items/_tree.html.erb
<% content_for :head do %>
  <%= javascript_tag "
    var loading = '#{escape_javascript Spree.t(:loading)}',
        new_menu = '#{escape_javascript Spree.t('navigator.admin.ajax.new_menu')}',
        server_error = '#{escape_javascript Spree.t(:server_error)}',
        menu_tree_error = '#{escape_javascript Spree.t('navigator.admin.ajax.menu_tree_error')}';

    $(document).ready(function(){
      setup_menu_tree();
    });
    "
  %>
<% end %>

<div id="ajax_error" class="errorExplanation" style="display:none;"></div>

<%= form_tag(admin_menu_items_path, method: :post) do |f| %>
  <fieldset class="no-border-top no-border-bottom">
    <%= label_tag nil, Spree.t(:tree) %>
    <script>
      Spree.routes.admin_menu_items_path = "<%= spree.admin_menu_items_path %>";
      Spree.routes.jstree_theme_path = "<%= stylesheet_path("jquery.jstree/themes/apple/style.css") %>";
    </script>

    <div id="menu_tree" class="tree"></div>

    <div id="progress" style="display:none;">
      <%= image_tag 'select2-spinner.gif', :title => 'Spinner', :style => "vertical-align:bottom;" %> <%= Spree.t(:updating) %>...
    </div>

    <div class="info"><%= Spree.t('navigator.admin.ajax.instructions') %></div>
  </fieldset>
<% end %>

app/views/spree/admin/menu_items/edit.html.erb
<%= render partial: 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t('navigator.admin.title.edit', name: @menu_item.name) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t('navigator.admin.button.back'), admin_menu_items_path, class: 'button' %></li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @menu_item } %>

<%= form_for @menu_item, url: admin_menu_item_path(@menu_item) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/spree/admin/menu_items/index.html.erb
<%= render partial: 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t('navigator.admin.title.index') %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'plus', Spree.t('navigator.admin.button.new'), new_admin_menu_item_path, class: 'button' %></li>
<% end %>

<% if @menu_items.any? %>
  <%= render partial: 'spree/admin/menu_items/tree' %>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t('navigator.admin.no_resource_found') %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_menu_item_path %>!
  </div>
<% end %>

app/views/spree/admin/menu_items/new.html.erb
<%= render partial: 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t('navigator.admin.title.new') %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t('navigator.admin.button.back'), admin_menu_items_path, class: 'button' %></li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @menu_item } %>

<%= form_for @menu_item, url: admin_menu_items_path do |f| %>
  <%= render 'form', f: f %>
<% end %>